version: "3.3"
services:
    app:
        container_name: 'microservice-image-optimizer'
        build: .
        command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80  
        volumes:
            - './:/code'
        ports:
            - '80:80'
        restart: always    
