version: "3.3"
services:
    app:
        container_name: 'microservice-image-optimizer'
        build: .
        command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000  
        volumes:
            - './:/app'
        ports:
            - '8000:8000'
        restart: always    
    redis:
        container_name: redis
        image: redis:6.2-alpine

    celery_worker:
        container_name: celery_worker
        build: .
        command: celery -A celery_worker.celery worker --loglevel=info
        volumes:
            - .:/app
        environment:
            - CELERY_BROKER_URL=${CELERY_BROKER_URL}
            - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        depends_on:
            - app
            - redis

    flower:
        container_name: flower
        build: .
        command: celery -A celery_worker.celery flower --port=5555
        ports:
            - 5556:5555
        environment:
            - CELERY_BROKER_URL=${CELERY_BROKER_URL}
            - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        depends_on:
            - app
            - redis
            - celery_worker
